Team page updated
IEEE-NITK/ieee-website-jekyll pull request #15
Opened 2021-11-10 14:36 UTC by madhavkumar1523

2021-11-10 14:47 UTC, madhavkumar1523 commented
![Screenshot from 2021-11-10 20-16-39](https://user-images.githubusercontent.com/77185670/141134713-873f153e-42eb-4a39-8c92-acc13b34c560.png
![Screenshot from 2021-11-10 20-16-49](https://user-images.githubusercontent.com/77185670/141134749-3f15e6a9-751a-4f49-9fd3-75f3ac29d383.png)
![Screenshot from 2021-11-10 20-16-54](https://user-images.githubusercontent.com/77185670/141134769-f2de4827-9bb5-4607-8302-a959e66edb76.png)
)

2021-11-10 15:36 UTC, gaurang2001 requested changes

2021-11-10 15:36 UTC, gaurang2001 commented on _data/team.json
> +    {
Put the new batch below current members, so the order of batches is preserved.

2021-11-10 15:36 UTC, gaurang2001 commented on team.html
> +        <div class="row">
So just adding it like this messes up the alignment - Copy the entire Faculty Members section from [https://github.com/IEEE-NITK/ieee-nitk.github.io/blob/master/team.html](https://github.com/IEEE-NITK/ieee-nitk.github.io/blob/master/team.html)

2021-11-16 19:26 UTC, gaurang2001 approved these changes

2021-11-16 19:28 UTC, merged